Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -16,8 +16,8 @@ jobs:
         uses: actions/checkout@v3    
         
       # Step 2: Check if Docker Image Exists
-      - name: Check if Docker Image Exists
-        id: check_image
+      - name: Check if Docker Image Exists savetofocus_backend
+        id: check_image_backend
         run: |
           REPOSITORY="${{ secrets.DOCKER_USERNAME }}/savetofocus_backend"  # Replace with your DockerHub repository name
           TAG="latest"
@@ -28,9 +28,22 @@ jobs:
           fi
           echo "Docker image exists. Proceeding to deployment."
 
+      # Step 2: Check if Docker Image Exists
+      - name: Check if Docker Image Exists savetofocus_frontend
+        id: check_image_frontend
+        run: |
+          REPOSITORY="${{ secrets.DOCKER_USERNAME }}/savetofocus_frontend"  # Replace with your DockerHub repository name
+          TAG="latest"
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_TOKEN }}" https://hub.docker.com/v2/repositories/${REPOSITORY}/tags/${TAG}/)
+          if [ "$RESPONSE" -ne 200 ]; then
+              echo "Docker image not found. Exiting workflow."
+              exit 1
+          fi
+          echo "Docker image exists. Proceeding to deployment."
+
       # Step 3: Set AWS Credentials in Environment Variables
       - name: Set AWS Credentials
-        if: ${{ steps.check_image.outcome == 'success' }}
+        if: ${{ steps.check_image_backend.outcome == 'success' && steps.check_image_frontend.outcome == 'success'}}
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -49,7 +62,7 @@ jobs:
           # Define instance details
           INSTANCE_ID=$(aws ec2 run-instances \
             --image-id ami-06b21ccaeff8cd686 \
-            --instance-type t2.micro \
+            --instance-type t2.medium \
             --key-name ${{ secrets.AWS_KP_NAME }} \
             --security-group-ids ${{ secrets.AWS_SG_ID }} \
             --user-data file://user-data.sh \
@@ -67,10 +80,44 @@ jobs:
             --query 'Reservations[0].Instances[0].PublicDnsName' \
             --output text)
           echo "Instance Public DNS: $INSTANCE_PUBLIC_DNS"
+          echo "INSTANCE_PUBLIC_DNS=$INSTANCE_PUBLIC_DNS" >> $GITHUB_ENV
 
-          aws ssm send-command \
-            --instance-ids "$INSTANCE_ID" \
-            --document-name "AWS-RunShellScript" \
-            --comment "Run Docker Backend" \
-            --parameters "commands=[sudo docker run -d -p 1337:1337 mysavev/savetofocus_backend]"
-          echo "Send Command to EC2 For Run Docker Backend"
+
+          INSTANCE_PUBLIC_IPV4=$(aws ec2 describe-instances \
+            --instance-ids $INSTANCE_ID \
+            --query 'Reservations[0].Instances[0].PublicIpAddress' \
+            --output text)
+          echo "Instance Public IPv4: $INSTANCE_PUBLIC_IPV4"
+          echo "INSTANCE_PUBLIC_IPV4=$INSTANCE_PUBLIC_IPV4" >> $GITHUB_ENV
+           
+      - name: Connect server and pull image Backend
+        env:
+            PRIVATE_KEY: ${{ secrets.AWS_KEY_PEM }}
+            #docker pull wuttipat6509650716/savetofocus_backend:latest
+            REPOSITORY: "${{ secrets.DOCKER_USERNAME }}/savetofocus_backend"
+            REPOSITORYFRONT: "${{ secrets.DOCKER_USERNAME }}/savetofocus_frontend"
+        run: |
+          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
+          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ env.INSTANCE_PUBLIC_DNS }} << EOF
+          sudo yum install -y docker
+          sudo service docker start
+          echo "BACKEND"
+          sudo docker pull $REPOSITORY:latest
+          sudo docker run -d --name backend_savetofocus \
+          -p 1337:1337 \
+          -e HOST=0.0.0.0 \
+          -e PORT=1337 \
+          -e STRAPI_ADMIN_CLIENT_URL=http://${INSTANCE_PUBLIC_IPV4}:3000/ \
+          -e STRAPI_ADMIN_CLIENT_PREVIEW_SECRET=${{ secrets.STRAPI_ADMIN_CLIENT_PREVIEW_SECRET }} \
+          -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
+          $REPOSITORY:latest
+          echo "FRONTEND"
+          sudo docker pull $REPOSITORYFRONT:latest
+          sudo docker run -d --name frontend_savetofocus \
+          -p 3000:3000 \
+          -e NEXT_PUBLIC_API_URL=http://${INSTANCE_PUBLIC_IPV4}:1337/ \
+          -e PREVIEW_SECRET=${{ secrets.STRAPI_ADMIN_CLIENT_PREVIEW_SECRET }} \
+          $REPOSITORYFRONT:latest
+          echo BackEnd http://${INSTANCE_PUBLIC_IPV4}:1337/
+          echo FrontEnd http://${INSTANCE_PUBLIC_IPV4}:3000/
+          EOF
